### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by Bigwode** [tjddus9597/Proxy-Anchor-CVPR2020#1]
Hello, I have seen some of the work of Metric Learning before. To ensure fairness, Most of them use the BN_Inception structure as the backbone, and use the output of the final gap layer as embedding. However, I see that the structure of gap + gmp is used in your code, but there is no description in the paper, but the points of other work reported in the paper are only using gap, can you explain and use gap at the same time And the number of gmp rise points.

**Comment by sung-yeon-kim** [comment]
Hello, thank you for your interest in our paper. Although there are differences between datasets, GMP improved by around 1% in the CUB-200-2011 and cars-196 datasets, and the results were similar to those used with GAP in the other datasets. We observed that similar performance gain is obtained even when only GMP is used as a protocol of MS loss.

Figure 1 of our paper shows a comparison with various methods including the recent SOTA method, MS loss. In the experiment of this figure, all the methods used the same architecture, and we observed that the proposed loss has an advantage in performance with a larger margin than the previous methods.

I think I should have described the implementation in more detail in the paper. Thank you for your great comments!

**Comment by Bigwode** [comment]
> Hello, thank you for your interest in our paper. Although there are differences between datasets, GMP improved by around 1% in the CUB-200-2011 and cars-196 datasets, and the results were similar to those used with GAP in the other datasets. We observed that similar performance gain is obtained even when only GMP is used as a protocol of MS loss.
> 
> Figure 1 of our paper shows a comparison with various methods including the recent SOTA method, MS loss. In the experiment of this figure, all the methods used the same architecture, and we observed that the proposed loss has an advantage in performance with a larger margin than the previous methods.
> 
> I think I should have described the implementation in more detail in the paper. Thank you for your great comments!

**Comment by Bigwode** [comment]
Thanks for your reply! 
   About GAP+GMP:
   I think the comparison with other SOTA in Table 2 in the paper is not fairness. For example, SoftTriple, which use only gap setting in their original realization, but in this paper, you only report the original metric in the SoftTriple paper but not gap+gmp setting.
   And other question, I run this code using CUB dataset following your instruction, but I got about 2% lower than your report. Could you please give me some advice?
R@1 : 67.657 ; R@2 : 77.819 ; R@4 : 85.533 ; R@8 : 91.053 ; R@16 : 94.581 ; R@32 : 96.860

**Comment by sung-yeon-kim** [comment]
We are sorry for the late reply.
First of all, to answer the first question, we thought that using GAP and GMP at the same time is a way to boost the performance of our loss without using additional parameters. We have not confirmed whether it is effective to apply this method to other losses, and comparing the performance of our loss with other losses using this method seems to be an interesting experiment. Although our method uses GAP + GMP, I think it is a very effective method in that it can achieve higher performance without using a large number of parameters, unlike HORDE or SoftTriple.

To answer another question, we did a lot of experiments before uploading the code and found that we get at least 68 performance at R@1. We experimented in the environment of torch 1.3.1 and python 3.7.4. Please check if there are any differences in the environment or hyperparameters such as batch size, and we hope that our code will be of great help to your work. :)

**Comment by EulerLee** [comment]
FYI.
[A BAG of TRICKS](https://arxiv.org/pdf/2004.01113.pdf)

**Comment by liuhl-source** [comment]
> Thanks for your reply!
> About GAP+GMP:
> I think the comparison with other SOTA in Table 2 in the paper is not fairness. For example, SoftTriple, which use only gap setting in their original realization, but in this paper, you only report the original metric in the SoftTriple paper but not gap+gmp setting.
> And other question, I run this code using CUB dataset following your instruction, but I got about 2% lower than your report. Could you please give me some advice?
> R@1 : 67.657 ; R@2 : 77.819 ; R@4 : 85.533 ; R@8 : 91.053 ; R@16 : 94.581 ; R@32 : 96.860

My results are same with you,. Do you have any solution of this problem?
