### ISSUE TITLE
Reproduce the performance in CUB

### ISSUE THREAD

**Issue by liuhl-source** [tjddus9597/Proxy-Anchor-CVPR2020#13]
Dose anyone reproduce the result in CUB successfully? My results is 67%@R1. Can you give me some advice? Thanks!!

**Comment by kdwonn** [comment]
I re-ran the scripts in readme several times and found it reproducible in my machine. However, from my experience, changing epochs of warm training (>= 5) might help sometimes. :)

**Comment by liuhl-source** [comment]
> I re-ran the scripts in readme several times and found it reproducible in my machine. However, from my experience, changing epochs of warm training (>= 5) might help sometimes. :)


> I re-ran the scripts in readme several times and found it reproducible in my machine. However, from my experience, changing epochs of warm training (>= 5) might help sometimes. :)

Thank you so much! How about SOP dataset, Are there any trick to reproduce, thanks!

**Comment by kdwonn** [comment]
In my case, no additional tweaks just for SOP was needed. Changing the warm training epoch also will help with SOP. However, few training settings should be changed due to the difference between fine-grained datasets and large-scale ones. You can find settings that differ in the training scripts provided(ex. batch-norm, lr, lr scheduling, epochs .. etc.).  Check out section 4.5 of our paper for further information!

**Comment by liuhl-source** [comment]
> In my case, no additional tweaks just for SOP was needed. Changing the warm training epoch also will help with SOP. However, few training settings should be changed due to the difference between fine-grained datasets and large-scale ones. You can find settings that differ in the training scripts provided(ex. batch-norm, lr, lr scheduling, epochs .. etc.). Check out section 4.5 of our paper for further information!

Thanks for your quick reply! but i have try it many times and the best performance is 78@R1(SOP) , 90.7@r1 (Inshop). Can you share your scripts or log files that I can figure out which step cause this performance gap. Thanks! liuhl@seu.edu.cn.

**Comment by kdwonn** [comment]
Sadly, codes and scripts on this repo are the latest versions I used. Did you use the exactly same code and scripts? Using the same package version( #7 ) might help, although I'm not sure... Let us know if you find anything helpful for reproducing results.

PS. One thing I forgot to mention in the previous comment is that longer training epochs would help on the large-scale datasets, on the other hand causing over-fitting in fine-grained ones. Try training with longer epochs.
