### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ShuteLee** [tjddus9597/Proxy-Anchor-CVPR2020#15]
I always get the “CUDA out of memory” error in the second training epoch.

OS: Ubuntu 20.04
GPU: RTX2080Super 8G
Pytorch: 1.6
CUDA: 10.1

I even set the batch size to 30, but it still report error.

Can anybody help me? Many thanks!

python test.py --gpu-id 0 --loss Proxy_Anchor --model resnet50 --embedding-size 512 --batch-size 60 --lr 1e-4 --dataset SOP --warm 0 --bn-freeze 1 --lr-decay-step 10
wandb: Currently logged in as: shute (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.10 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.8
wandb: Syncing run desert-gorge-52
wandb: ⭐️ View project at https://wandb.ai/shute/SOP_ProxyAnchor
wandb: 🚀 View run at https://wandb.ai/shute/SOP_ProxyAnchor/runs/2tahb6vq
wandb: Run data is saved locally in wandb/run-20201116_032833-2tahb6vq
wandb: Run `wandb off` to turn off syncing.

Random Sampling
Training parameters: {'LOG_DIR': '../logs', 'dataset': 'SOP', 'sz_embedding': 512, 'sz_batch': 60, 'nb_epochs': 60, 'gpu_id': 0, 'nb_workers': 4, 'model': 'resnet50', 'loss': 'Proxy_Anchor', 'optimizer': 'adamw', 'lr': 0.0001, 'weight_decay': 0.0001, 'lr_decay_step': 10, 'lr_decay_gamma': 0.5, 'alpha': 32, 'mrg': 0.1, 'IPC': None, 'warm': 0, 'bn_freeze': 1, 'l2_norm': 1, 'remark': ''}
Training for 60 epochs.
Train Epoch: 0 [992/992 (100%)] Loss: 10.767641: : 992it [04:41,  3.52it/s]**Evaluating...**

100%|██████████| 1009/1009 [01:26<00:00, 11.69it/s]
R@1 : 0.020
R@10 : 0.159
R@100 : 1.397
R@1000 : 12.509
Train Epoch: 1 [992/992 (100%)] Loss: 10.454696: : 992it [04:41,  3.52it/s]
**Evaluating...**
100%|██████████| 1009/1009 [01:25<00:00, 11.77it/s]
Traceback (most recent call last):
  File "test.py", line 321, in <module>
    Recalls = utils.evaluate_cos_SOP(model, dl_ev)
  File "/home/server8/lst/Proxy-Anchor/Proxy-Anchor-CVPR2020-master/code/utils.py", line 148, in evaluate_cos_SOP
    cos_sim = F.linear(xs,X)
  File "/home/server8/anaconda3/envs/proj/lib/python3.8/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 2.26 GiB (GPU 0; 7.80 GiB total capacity; 2.85 GiB already allocated; 1.26 GiB free; 5.56 GiB reserved in total by PyTorch)

wandb: Waiting for W&B process to finish, PID 2010371
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Find user logs for this run at: wandb/run-20201116_032833-2tahb6vq/logs/debug.log
wandb: Find internal logs for this run at: wandb/run-20201116_032833-2tahb6vq/logs/debug-internal.log
wandb: Run summary:
wandb:         loss 9.7143
wandb:          R@1 0.0002
wandb:         R@10 0.00159
wandb:        R@100 0.01397
wandb:       R@1000 0.12509
wandb:        _step 1
wandb:     _runtime 745
wandb:   _timestamp 1605516058
wandb: Run history:
wandb:         loss █▁
wandb:          R@1 ▁
wandb:         R@10 ▁
wandb:        R@100 ▁
wandb:       R@1000 ▁
wandb:        _step ▁█
wandb:     _runtime ▁█
wandb:   _timestamp ▁█
wandb: 
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced desert-gorge-52: https://wandb.ai/shute/SOP_ProxyAnchor/runs/2tahb6vq

**Comment by kdwonn** [comment]
Hello!

It seems like an error occur when calculating the cosine similarity between every embedding.
I'm pretty sure that changing line 143 of utils.py like the following will fix this issue. It will reduce the number of embedding used at each step to calculate the similarity matrix (It will make the evaluation a little bit slower). 

`if len(xs)<[SOME VALUE SMALLER THAN 10000]:`

Let me know whether this modification works. Thanks! :smile:

**Comment by FightStone** [comment]
@ShuteLee Have you solved this problem? Even if I don’t use evaluation, OOM will also appear in the second round of training.

**Comment by ShuteLee** [comment]
> @ShuteLee Have you solved this problem? Even if I don’t use evaluation, OOM will also appear in the second round of training.

What's your batch size? I set 60 on my Rtx2080

**Comment by FightStone** [comment]
Thank you for your quick reply. I am using 1080ti, GPU11G, resnet101, batchsize=180

**Comment by kdwonn** [comment]
Batch size seems too big. Try it with smaller size. Note that training scripts in README is based on setting using two TITAN XP(12G).

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: FightStone <notifications@github.com>
보낸 날짜: Wednesday, December 30, 2020 6:56:11 PM
받는 사람: tjddus9597/Proxy-Anchor-CVPR2020 <Proxy-Anchor-CVPR2020@noreply.github.com>
참조: 김동원 <kdwon@postech.ac.kr>; State change <state_change@noreply.github.com>
제목: Re: [tjddus9597/Proxy-Anchor-CVPR2020] CUDA out of memory (#15)


Thank you for your quick reply. I am using 1080ti, GPU11G, resnet101, batchsize=180

**Comment by FightStone** [comment]
@kdwonn 1. But why can the first epoch go on in one 1080ti? 2. How to use multiple GPUs for training?

**Comment by sung-yeon-kim** [comment]
First epoch is used for warm-up training.
In the first epoch, the remaining parameters are freeze except for the proxies and the last embedding layer, so the memory usage is low.

**Comment by FightStone** [comment]
@tjddus9597 great！Do you know how to use multiple GPUs for training?

**Comment by kdwonn** [comment]
Simply giving —gpu-id -1 as argument of train.py will do it. :)

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: FightStone <notifications@github.com>
보낸 날짜: Wednesday, December 30, 2020 7:24:32 PM
받는 사람: tjddus9597/Proxy-Anchor-CVPR2020 <Proxy-Anchor-CVPR2020@noreply.github.com>
참조: 김동원 <kdwon@postech.ac.kr>; Mention <mention@noreply.github.com>
제목: Re: [tjddus9597/Proxy-Anchor-CVPR2020] CUDA out of memory (#15)


@tjddus9597<https://github.com/tjddus9597> great！Do you know how to use multiple GPUs for training?

**Comment by sung-yeon-kim** [comment]
Our code supports multi parallel for multi-gpu use. If you use the gpu-id with -1 in parser, it will learn using all the gpu you have. 
If you only want to use a specific gpus, set the gpu-id to -1 and set CUDA_VISIBLE_DEVICES before the executable script.

**Comment by FightStone** [comment]
@tjddus9597 @kdwonn Thanks for your replies！
