### ISSUE TITLE
[UPDATE to code/train.py ]  criterion = losses.Proxy_NCA().cuda()

### ISSUE THREAD

**Issue by moured** [tjddus9597/Proxy-Anchor-CVPR2020#16]
Thanks for this great work !! 

I would like to suggest a minor update for a bug that I have found.

**ERROR**
If you use Proxy_NCA you will most probably get this error : 
TypeError: __init__() missing 2 required positional arguments: 'nb_classes' and 'sz_embed'

**Solution:** 
Line 225 in code/train.py ->   criterion = losses.Proxy_NCA().cuda()
change it to : 
criterion = losses.Proxy_NCA(nb_classes = nb_classes, sz_embed = args.sz_embedding).cuda()

Thanks again,
Moured

**Comment by kdwonn** [comment]
Thank you for your interest! We'll update the code for that error soon.
