### ISSUE TITLE
Using gt box or expanding gt box?

### ISSUE THREAD

**Issue by FightStone** [tjddus9597/Proxy-Anchor-CVPR2020#17]
Thanks for open source, when you train the model on In-shop, the clothes are closely croped according to gt-box? Or expand the gt box in the cropping clothes? I think this will affect the image preprocessing in the algorithm. Looking forward to your reply.

**Comment by sung-yeon-kim** [comment]
Sorry for the late reply. 
First of all, as you say, cropping using gt-box is very effective, and it is a way to increase performance significantly.
However, it is unfair to use gt-box in common methods of deep metric learning, so we didn't use it in our experiments.
If your experiment is in an environment where you can use gt-box, cropping using it will be very effective.

**Comment by FightStone** [comment]
When you use the gt boxes in your estimation, the centercrop will only get part of the target information, which I think affects the performance of the algorithm. is that right?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sungyeon&amp;nbsp;Kim&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月8日(星期一) 晚上10:06
收件人:&nbsp;&quot;tjddus9597/Proxy-Anchor-CVPR2020&quot;<Proxy-Anchor-CVPR2020@noreply.github.com&gt;;
抄送:&nbsp;&quot;FightStone&quot;<864345476@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tjddus9597/Proxy-Anchor-CVPR2020] Using gt box or expanding gt box? (#17)

**Comment by sung-yeon-kim** [comment]
As you say, center cropping on a cropped image can drop performance. 
In the case of using a cropped dataset, I know that it is generally training and evaluated using only scaling.
There are some papers that evaluate using the cropped dataset, so it would be nice to read them.
- "Sampling Matters in Deep Embedding Learning"
- "Attention-based Ensemble for Deep Metric Learning"
