### ISSUE TITLE
random sampling

### ISSUE THREAD

**Issue by EulerLee** [tjddus9597/Proxy-Anchor-CVPR2020#2]
Thank you for sharing your code. Nice work! But I got confused about the sampling method.
I see that the random sampler is used in your code. In this case, for a specific p &in; P<sup>+</sup>, |X<sub>p</sub><sup>+</sup>| is equal to 1 with a high probability. Since  |X<sub>p</sub><sup>+</sup>| is usually no more than 1, there is no "the most dissimilar positive example" to mine. Then do we still need the complicated smooth method of positive sample pairs in your loss function?
I would be appreciated if you could unravel my doubts.

**Comment by sung-yeon-kim** [comment]
Thank you for your interest in our method. In the experimental dataset, when the batch is small, the number of positive samples can be 1 with a high probability. However, the positive term of the proposed loss is more meaningful when the batch becomes large (at least 150 or higher) or when it is applied to a data set with few classes (e.g. MNIST). In general, it will be more effective than considering only one positive sample.

**Comment by EulerLee** [comment]
Thanks for your reply.  But I still wonder why didn't you apply PK-sampler to solve the issue of few positive pairs?

**Comment by sung-yeon-kim** [comment]
The PK-sampler did not give a positive effect on our loss because it can reduce |P^+| of our loss and a large number of proxies cannot be considered in one iteration. In addition, random sampling eliminates the phase of batch generation, so it has the advantage of enabling faster learning.

**Comment by jlian2** [comment]
Could you please give a bit more details on your last reply? What does it mean by "reduce |P^+| of our loss"? |P^+|  is defined just in a batch.

**Comment by sung-yeon-kim** [comment]
If we construct a batch using the PK-sampler, the size of the batch is the product of the number P of classes, and the number K of samples belonging to the class. The last reply means that when a batch is given, the number of positive proxy in the batch decreases as K increases.

**Comment by Xiangyu-CAS** [comment]
Hi, I have a question about using random sampler, it's saying "when the batch is small, the number of positive samples can be 1 with a high probability".
However, in industry, when there are million identies, the probability of without positive pair can be 100%, even we use a really large batch size like up to 2048. Would your algorithm works as well?
