### ISSUE TITLE
Evaluation on ReID datasets

### ISSUE THREAD

**Issue by itsnamgyu** [tjddus9597/Proxy-Anchor-CVPR2020#21]
Do you have any plans to evaluate your loss on ReID datasets? If not, would it be okay for me to implement them in my repo for ReID and share it with you guys? Thanks.

**Comment by sung-yeon-kim** [comment]
Unfortunately, we do not currently intend to evaluate our loss on the ReID datasets. 
I would really appreciate it if you reproduce the Proxy-Anchor loss on the datasets. 
If you get performance with the loss and share it, I'll mention your repo in our repo. :D
