### ISSUE TITLE
model.model.embedding bug

### ISSUE THREAD

**Issue by jjkim0807** [tjddus9597/Proxy-Anchor-CVPR2020#23]
기존 모델의 FNN 모델부분이었던 model.model.embedding을 현재 model.cgd 안쪽으로 다 넣어두었는데,
훈련 모델에서 해당 파라미터에 속하지 않는 파라미터만 골라서 unfreeze하거나 freeze하는 기능이 구현되어있어 문제가 있음.
model.cgd 안쪽의 파라미터들을 model.embedding 쪽으로 넘겨주던지, 다른 방법을 강구해야 함.

**Comment by kdwonn** [comment]
model.cgd 가 어디를 말하는 것인지요? file name과 line number 첨부해서 좀 더 자세히 적어주세요.
