### ISSUE TITLE
BalancedSampler is highly inefficient and way too slow for even dataset with mild size

### ISSUE THREAD

**Issue by jdhao** [tjddus9597/Proxy-Anchor-CVPR2020#26]
Okay, I tried the BalancedSampler provided and find that it is way too slow for larger datasets, say 50000 class and 10 images for each class.

I did some benchmark and find that the issue is with [this line](https://github.com/tjddus9597/Proxy-Anchor-CVPR2020/blob/3df643b36d62a46e7d90d68bd476521fba65e9d5/code/dataset/sampler.py#L26):

> ith_class_idxs = np.nonzero(np.array(self.ys) == sampled_classes[i])[0]

You are repeated initializing a numpy array from `self.ys`, which is time consuming. One way to fix this is to initialize the self.ys as a numpy array in `__init__()`. Do you want me to fix this? I would be happy to provide a PR.

**Comment by sung-yeon-kim** [comment]
Sorry for the late reply.
It seems that a big bottleneck occurs in the part you commented on. 
I will edit the corresponding line. 
Thanks for the PR.
