### ISSUE TITLE
Distance measure

### ISSUE THREAD

**Issue by jlian2** [tjddus9597/Proxy-Anchor-CVPR2020#3]
In the original ProxyNCA loss, distance measure seems to be "L2 distance". But in your paper, when you cite ProxyNCA loss, you mention it is "cosine similarity"?

**Comment by sung-yeon-kim** [comment]
As you say, ProxyNCA loss is designed with euclidean distance in the original paper. But when L2 normalization is taken, there is no significant difference due to the euclidean distance becomes proportional to cosine distance.
