### ISSUE TITLE
Experimental results using other methods

### ISSUE THREAD

**Issue by kdhht2334** [tjddus9597/Proxy-Anchor-CVPR2020#6]
Hi,

I have a question about experimental results using other methods such as MS.

Did you get experimental results of MS yourself or just use MS paper's result as it is?

I'm so happy to receive your response.

Thanks

**Comment by kdwonn** [comment]
Hi,

**Comment by kdwonn** [comment]
Hi,

**Comment by kdwonn** [comment]
Thank you for your interest in our method. For the experiments presented in figure 1, we re-implemented other losses or used the implementation of public repositories. You can find nice implementations in [here](https://github.com/KevinMusgrave/pytorch-metric-learning) or [here](https://github.com/Confusezius/Deep-Metric-Learning-Baselines).

**Comment by kdhht2334** [comment]
Thanks for quick reply!

It would be very helpful.


Regards,

Dae Ha Kim.
PhD student

Department of Electronic Engineering

Inha University

Incheon, 22212, Republic of Korea

====================================================



2020년 6월 30일 (화) 오후 7:21, Dongwon Kim <notifications@github.com>님이 작성:
