### ISSUE TITLE
How did you leverage data-to-proxy relationship?

### ISSUE THREAD

**Issue by jlian2** [tjddus9597/Proxy-Anchor-CVPR2020#9]
Once I compare Proxy Anchor with Proxy NCA, there is no significant difference. What does Proxy Anchor do still focuses on s(x,p) rather than s(x,x). And what is the difference between s(x,p) and s(p,x)? Regard x as anchor, then you need compute x * p pairs. Regard p as anchor, then you need compute p * x pairs? What is the difference? I notice the difference is that Proxy Anchor attributes different weights for different pairs? But you are still doing with data-to-proxy relationship. ?

**Comment by darkpromise98** [comment]
The author says 'it enables embedding vectors of data points to be affected by each other through its gradients' in original paper. And in Equation 6, we may note that the gradient of certain x is built on different x in a batch.  I think the author considers this can 'leverage data-to-proxy relationship'.  Although it's farfetched...
